application: igreddit
version: 1
runtime: python
api_version: 1

handlers:

- url: /xml
  static_dir: xml

- url: /css
  static_dir: css

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /screenshot.png
  static_files: static/screenshot.png
  upload: static/screenshot.png

- url: /thumb.png
  static_files: static/thumb.png
  upload: static/thumb.png

- url: /
  script: main.py